name: 'release'

on:
  release:
    types: [ published ]

jobs:
  release:
    runs-on: 'ubuntu-latest'
    container:
      image: 'n7st/distzilla:5.37.0'
    steps:
      - name: 'Check out the code'
        uses: 'actions/checkout@v3'
      - uses: actions-ecosystem/action-release-label@v1
        id: release-label
        if: ${{ github.event.pull_request.merged == true }}
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        if: ${{ steps.release-label.outputs.level != null }}
      - name: 'Check out the code'
        uses: 'actions/checkout@v3'
        with:
          ref: ${{ steps.release-label.outputs.level }}
      - name: 'Install dependencies'
        run: |
          dzil authordeps --missing | xargs -n 5 -P 10 cpanm --no-interactive --notest --quiet
          dzil listdeps --missing --author | xargs -n 5 -P 10 cpanm --no-interactive --notest --quiet
      - name: 'Create the credential file'
        env:
          PAUSE_USERNAME: ${{ secrets.PAUSE_USERNAME }}
          PAUSE_PASSWORD: ${{ secrets.PAUSE_PASSWORD }}
        run: |
          mkdir -p ~/.dzil
          /bin/echo -e "[%PAUSE]\\nusername=${PAUSE_USERNAME}\\npassword=${PAUSE_PASSWORD}\\n" > ~/.dzil/config.ini
      - name: 'Release to PAUSE'
        env:
          DZIL_CONFIRMRELEASE_DEFAULT: 'yes'
        run: |
          dzil release

