name: 'release'

on:
  release:
    types: [ published ]

jobs:
  release:
    runs-on: 'ubuntu-latest'
    container:
      image: 'n7st/distzilla:5.32.0'
    steps:
      - name: 'Get git version'
        run: git --version
      - name: 'Check out the code'
        uses: 'actions/checkout@v2'
      - name: 'Check out tag'
        run: git checkout ${GITHUB_REF#refs/*/}
      - name: 'Install dependencies'
        run: |
          dzil authordeps --missing | xargs -n 5 -P 10 cpanm --no-interactive --notest --quiet
          dzil listdeps --missing --author | xargs -n 5 -P 10 cpanm --no-interactive --notest --quiet
      - name: 'Create the credential file'
        env:
          PAUSE_USERNAME: ${{ secrets.PAUSE_USERNAME }}
          PAUSE_PASSWORD: ${{ secrets.PAUSE_PASSWORD }}
        run: |
          mkdir -p ~/.dzil
          /bin/echo -e "[%PAUSE]\\nusername=${PAUSE_USERNAME}\\npassword=${PAUSE_PASSWORD}\\n" > ~/.dzil/config.ini
      - name: 'Release to PAUSE'
        env:
          DZIL_CONFIRMRELEASE_DEFAULT: 'yes'
        run: |
          PERL5LIB=t dzil release

